<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;

class SiteController extends Controller
{
    public function index()
    {
$productsCats = [
    [
        'id' => '1',
        'title' => 'قهوه دان',
        'image' => null,
        'active' => '1',
        'products' => [
            [
                'id' => '1',
                'index' => '0',
                'product_category_id' => '1',
                'title' => 'دانه قهوه اورو 80% عربیکا_ 20% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => 'قهوه ترکیبی با برشتگی متوسط و غلظت ملایم.',
                'image1' => '/images/products/product_1_67a35f6cdc384.png',
                'image2' => '/images/products/2.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:54:04',
            ],
            [
                'id' => '2',
                'index' => '0',
                'product_category_id' => '1',
                'title' => 'دانه قهوه اورو 100% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => 'غلظت بالا، کافئین زیاد و برشتگی تیره.',
                'image1' => '/images/products/product_2_67a35f9023ccc.png',
                'image2' => '/images/products/4.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:54:40',
            ],
            [
                'id' => '3',
                'index' => '0',
                'product_category_id' => '1',
                'title' => 'دانه قهوه اورو 70% روبوستا_ 30% عربیکا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => 'غلظت و کافئین نسبتا بالا با برشتگی تیره',
                'image1' => '/images/products/product_3_67a35fb6008e0.png',
                'image2' => '/images/products/5.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:55:18',
            ],
            [
                'id' => '4',
                'index' => '0',
                'product_category_id' => '1',
                'title' => 'دانه قهوه 50% عربیکا 50% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => 'ترکیبی مساوی از عربیکا و ربوستا با برشتگی نسبتا تیره.',
                'image1' => '/images/products/product_4_67a360015ca83.png',
                'image2' => '/images/products/8.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:56:33',
            ],
            [
                'id' => '5',
                'index' => '0',
                'product_category_id' => '1',
                'title' => 'دانه قهوه اورو 100% عربیکا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => 'دانه قهوه عربیکا خالص با برشتگی متوسط',
                'image1' => '/images/products/product_5_67a361b4e371d.png',
                'image2' => '/images/products/9.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 13:03:48',
            ],
        ],
    ],

    [
        'id' => '2',
        'title' => 'قهوه پودر',
        'image' => null,
        'active' => '1',
        'products' => [
            [
                'id' => '32',
                'index' => '0',
                'product_category_id' => '2',
                'title' => 'پودر قهوه اورو 100% عربیکا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_32_67a358f3ccdc6.png',
                'image2' => '/images/products/product_32_67a358f406413.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 12:26:27',
                'updated_at' => '2025-02-05 12:41:26',
            ],
            [
                'id' => '33',
                'index' => '0',
                'product_category_id' => '2',
                'title' => 'پودر قهوه 50% عربیکا 50% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_33_67a35ad4a1bff.png',
                'image2' => '/images/products/product_33_67a35ad4b95c0.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 12:34:28',
                'updated_at' => '2025-02-05 12:41:23',
            ],
            [
                'id' => '34',
                'index' => '0',
                'product_category_id' => '2',
                'title' => 'پودر قهوه اورو 80% عربیکا_ 20% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_34_67a35b2b25e6f.png',
                'image2' => '/images/products/product_34_67a35b2b3d52b.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 12:35:55',
                'updated_at' => '2025-02-05 12:41:23',
            ],
            [
                'id' => '35',
                'index' => '0',
                'product_category_id' => '2',
                'title' => 'پودر قهوه اورو 70% روبوستا_ 30% عربیکا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_35_67a35bf245a23.png',
                'image2' => '/images/products/product_35_67a35bf25d7d3.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 12:39:14',
                'updated_at' => '2025-02-05 12:41:21',
            ],
            [
                'id' => '36',
                'index' => '0',
                'product_category_id' => '2',
                'title' => 'پودر قهوه 100% روبوستا',
                'subTitle' => '250 گرم',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_36_67a35c64d347f.png',
                'image2' => '/images/products/product_36_67a35c6504fb7.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 12:41:08',
                'updated_at' => '2025-02-05 12:41:21',
            ],
        ],
    ],

    [
        'id' => '3',
        'title' => 'قهوه فوری',
        'image' => null,
        'active' => '1',
        'products' => [
            [
                'id' => '6',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 4x1 آیریش کریم کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_6_679f367c3b655.png',
                'image2' => '/images/products/product_6_679f5b5acaa42.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:44:55',
            ],
            [
                'id' => '7',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 2x1 لاته کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => '1*2',
                'image1' => '/images/products/product_7_679f3637d073e.png',
                'image2' => '/images/products/product_7_679f5ad39ddf2.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:45:12',
            ],
            [
                'id' => '8',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 4x1 فندقی کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => 'توصیحات',
                'image1' => '/images/products/product_8_679f3582d007e.png',
                'image2' => '/images/products/product_8_679f5bc94b6a1.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:46:57',
            ],
            [
                'id' => '9',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کوپا هات چاکلت',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => 'توصیحات',
                'image1' => '/images/products/product_9_679f351dbef4f.png',
                'image2' => '/images/products/product_9_679f71247372d.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:46:37',
            ],
            [
                'id' => '10',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 3x1 کلاسیک کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => 'توصیحات',
                'image1' => '/images/products/product_10_679f34cfafffb.png',
                'image2' => '/images/products/product_10_679f5aae2517f.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:46:16',
            ],
            [
                'id' => '11',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 4x1 موکا کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_11_679f348dbf116.png',
                'image2' => '/images/products/product_11_679f5b94493da.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-05 12:45:58',
            ],
            [
                'id' => '22',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'باکس کافی‌میکس 4x1 وانیلی کوپاکافه',
                'subTitle' => 'باکس 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_22_679f44f2594f8.png',
                'image2' => '/images/products/product_27_67a0b4107223d.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-02 10:12:02',
                'updated_at' => '2025-02-05 12:43:56',
            ],
            [
                'id' => '18',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'کاپوچینو کوپاکافه 1*5',
                'subTitle' => 'ساشه 25 گرمی',
                'ingredients' => null,
                'text' => 'توصیحات',
                'image1' => '/images/products/product_18_679f31ea1ef0f.png',
                'image2' => '/images/products/product_18_679f31ea4434a.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-02 08:50:50',
            ],
            [
                'id' => '43',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کافی‌میکس 4x1 آیریش کریم کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_43_67a36fc0e4b8c.png',
                'image2' => '/images/products/product_6_679f5b5acaa42.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 14:03:44',
                'updated_at' => '2025-02-05 14:17:17',
            ],
            [
                'id' => '30',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کافی‌میکس 2x1 لاته کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_30_67a0b62c25255.png',
                'image2' => '/images/products/product_7_679f5ad39ddf2.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:27:24',
                'updated_at' => '2025-02-05 13:07:59',
            ],
            [
                'id' => '31',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عدد کافی‌میکس 4x1 فندقی کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_31_67a0b739c96f3.png',
                'image2' => '/images/products/product_8_679f5bc94b6a1.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:31:53',
                'updated_at' => '2025-02-05 12:44:28',
            ],
            [
                'id' => '29',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کوپا هات چاکلت',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_29_67a0b52010cbb.png',
                'image2' => '/images/products/product_29_67a0b5205f894.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:22:56',
                'updated_at' => '2025-02-05 12:45:40',
            ],
            [
                'id' => '26',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کافی‌میکس 3x1 کلاسیک کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_26_67a0b2be179d4.png',
                'image2' => '/images/products/product_10_679f5aae2517f.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:12:46',
                'updated_at' => '2025-02-05 13:06:57',
            ],
            [
                'id' => '28',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کافی‌میکس 4x1 موکا کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_28_67a0b49c6dab6.png',
                'image2' => '/images/products/product_28_67a0b49cccedc.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:20:44',
                'updated_at' => '2025-02-05 13:07:38',
            ],
            [
                'id' => '27',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 20 عددی کافی‌میکس 4x1 وانیلی کوپاکافه',
                'subTitle' => 'بسته 20 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_27_67a0b41014b43.png',
                'image2' => '/images/products/product_27_67a0b4107223d.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-03 12:18:24',
                'updated_at' => '2025-02-05 13:07:18',
            ],
            [
                'id' => '41',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 4x1 آیریش کریم کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_41_67a36cd9c386f.png',
                'image2' => '/images/products/product_41_67a36cda12e08.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:51:21',
                'updated_at' => '2025-02-05 13:53:06',
            ],
            [
                'id' => '44',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 2x1 لاته کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_44_67a372d5deca8.png',
                'image2' => '/images/products/product_44_67a372d628ee1.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 14:16:53',
                'updated_at' => '2025-02-05 14:17:08',
            ],
            [
                'id' => '38',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 4x1 فندقی کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_38_67a36b79af43c.png',
                'image2' => '/images/products/product_38_67a36b79cd108.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:45:29',
                'updated_at' => '2025-02-05 13:45:34',
            ],
            [
                'id' => '42',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کوپا هات چاکلت',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_42_67a36d3dede4c.png',
                'image2' => '/images/products/product_42_67a36d3e247d5.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:53:01',
                'updated_at' => '2025-02-05 13:53:05',
            ],
            [
                'id' => '40',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 3x1 کلاسیک کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_40_67a36c41b9461.png',
                'image2' => '/images/products/product_40_67a36c420ae32.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:48:49',
                'updated_at' => '2025-02-05 13:53:07',
            ],
            [
                'id' => '39',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 4x1 موکا کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_39_67a36bbb7db14.png',
                'image2' => '/images/products/product_39_67a36bbb9b78c.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:46:35',
                'updated_at' => '2025-02-05 13:46:39',
            ],
            [
                'id' => '37',
                'index' => '0',
                'product_category_id' => '3',
                'title' => 'بسته 40 عددی کافی‌میکس 4x1 وانیلی کوپاکافه',
                'subTitle' => 'بسته 40 عددی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_37_67a36b1eda264.png',
                'image2' => '/images/products/product_37_67a36b1f1c277.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => '2025-02-05 13:43:58',
                'updated_at' => '2025-02-05 13:44:05',
            ],
        ],
    ],

    [
        'id' => '4',
        'title' => 'قهوه گلد',
        'image' => null,
        'active' => '1',
        'products' => [
            [
                'id' => '21',
                'index' => '0',
                'product_category_id' => '4',
                'title' => 'قهوه گلد کونیگ 90 گرمی کوپاکافه',
                'subTitle' => '90 گرمی',
                'ingredients' => null,
                'text' => 'توضیحات',
                'image1' => '/images/products/product_21_679f3b1e60f87.png',
                'image2' => '/images/products/product_21_679f3b1e80585.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-02 12:11:38',
            ],
            [
                'id' => '23',
                'index' => '0',
                'product_category_id' => '4',
                'title' => 'قهوه گلد کونیگ 170 گرمی کوپاکافه',
                'subTitle' => '170 گرمی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_23_679f61debd7af.png',
                'image2' => '/images/products/product_23_679f60b013fef.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-02 12:15:26',
            ],
        ],
    ],

    [
        'id' => '5',
        'title' => 'کریمر',
        'image' => null,
        'active' => '1',
        'products' => [
            [
                'id' => '20',
                'index' => '0',
                'product_category_id' => '5',
                'title' => 'کریمر 200 گرمی کوپاکافه',
                'subTitle' => '200 گرمی',
                'ingredients' => null,
                'text' => 'توصیحات',
                'image1' => '/images/products/product_20_679f62eb8f6b9.png',
                'image2' => '/images/products/product_20_679f62eb8f6b9.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-02 12:19:55',
            ],
            [
                'id' => '24',
                'index' => '0',
                'product_category_id' => '5',
                'title' => 'کریمر 400 گرمی کوپاکافه',
                'subTitle' => '400 گرمی',
                'ingredients' => null,
                'text' => null,
                'image1' => '/images/products/product_24_679f6377bba9e.png',
                'image2' => '/images/products/product_24_679f6377e91db.png',
                'stock' => '0',
                'features' => null,
                'active' => '1',
                'price' => '0',
                'link' => null,
                'off' => '0',
                'view' => '0',
                'sale' => '0',
                'score' => '0.00',
                'score_count' => '0',
                'created_at' => null,
                'updated_at' => '2025-02-02 12:23:28',
            ],
        ],
    ],
];
        foreach ($productsCats as $item){
            Category::create([
                'id' => $item['id'],
                'title' => $item['title'],
                'visible' => 1,
            ]);
            foreach ($item['products'] as $pro ){
                Product::create([
                    'id' => $pro['id'],
                    'index' => 0,
                    'product_category_id' => $pro['product_category_id'],
                    'title' => $pro['title'],
                    'subTitle' => $pro['subTitle'],
                    'text' => $pro['text'],
                    'image1' => $pro['image1'],
                    'image2' => $pro['image2'],
                    'visible' => 1,
                ]);
            }
        }

        return 'ok';
    }
}
